//This file was generated by script mkregs.py

//register address mapping
#define KNN_RESET 0
#define KNN_ENABLE 1
#define KNN_X 2
#define KNN_Y 3
#define KNN_INFO 4
#define KNN_ID 5
#define KNN_READY 6
