//This file was generated by script mkregs.py

//address macros
`define KNN_RESET_ADDR 0
`define KNN_ENABLE_ADDR 1
`define KNN_X_ADDR 2
`define KNN_Y_ADDR 3
`define KNN_LABEL_ADDR 4
`define KNN_DIST_ADDR 5

//registers width
`define KNN_RESET_W 1
`define KNN_ENABLE_W 1
`define KNN_X_W 32
`define KNN_Y_W 32
`define KNN_LABEL_W 8
`define KNN_DIST_W 32
